In [ ]:
# Basic 
# introduction array array indexing array slicing

# we pass slice instead of index like this star: end

# start : end : step
# 0

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:3])

[2 3]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[1:])

[2 3 4 5 6 7]


In [ ]:
print(arr[1:6:2])

[2 4 6]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2[1, 1:3])

[6 7]


In [ ]:
print(arr2[0:2, 2])

[3 7]


In [ ]:
print(arr2[0:2,1:3])

[[2 3]
 [6 7]]


In [ ]:
# data type in numpy
# i = integer
# b == boolean
# u = unsigned ineger
# f float
# c = complex
# m timedelta
# M datetime
# o object
# S string
# U unicode string
# V fix chunk o fmemory fro othe type


In [ ]:
print(arr.dtype)

int64


In [ ]:
arr3 = np.array(["apple","mango"])
print(arr3.dtype)

<U5


In [ ]:
arr4 = np.array([1,2,3,4,5,6,7], dtype = 'S')
print(arr4.dtype)

|S1


In [ ]:
arr4[0] = 42
print(arr4)

[b'4' b'2' b'3' b'4' b'5' b'6' b'7']


In [ ]:
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


In [ ]:
x = arr.copy()
arr[1] = 34
print(arr)
print(x)

[42 34  3  4  5  6  7]
[42  2  3  4  5  6  7]
