### Diffrence Between Array vs List

In [ ]:
import numpy as np
arr1=np.array([1,4,7,3,8])
print("My array is: ",arr1)

myList=[3,8,5,3]
print("MyList is: ",myList)

My array is:  [1 4 7 3 8]
MyList is:  [3, 8, 5, 3]


In [ ]:
%timeit [i*2 for i in range(1,21)]

631 ns ± 183 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
%timeit np.arange(1,21)*2

2.58 μs ± 289 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
linspace=np.linspace(0,20,num=5)
print("LinSpace: ",linspace)

LinSpace:  [ 0.  5. 10. 15. 20.]


### Random Array Creation

In [ ]:
var1=np.random.rand(5)
var2=np.random.rand(3,3)
var3=np.random.randn(5)
var4=np.random.randn(3,4)
var5=np.random.ranf(5)
var6=np.random.ranf((4,5))
var7=np.random.randint(4,10,6)
print("Random 1d Array Between 0 to 1:",var1)
print("Random 2d Array Between 0 to 1:",var2)
print("Random 1d Array Between 0 to 1 Negative Positive:",var3)
print("Random 2d Array Between 0 to 1 Negative Positive:",var4)
print("Random 1d Array Between 0 to 1:",var5)
print("Random 2d Array Between 0 to 1:",var6)
print("Random 1d Array Between 0 to 1:",var7)

Random 1d Array Between 0 to 1: [0.74478411 0.49474288 0.00912236 0.94724858 0.41828432]
Random 2d Array Between 0 to 1: [[0.9880146  0.89012266 0.08026685]
 [0.79664921 0.88689376 0.68973136]
 [0.67767722 0.93473338 0.68056556]]
Random 1d Array Between 0 to 1 Negative Positive: [ 0.67358922  1.03830634 -1.83510677 -0.81576908 -0.71842464]
Random 2d Array Between 0 to 1 Negative Positive: [[ 0.1797396  -1.01418137  0.40251126  1.67592984]
 [ 2.30194868  1.00998866  1.40411531  0.37417928]
 [ 1.23563731  0.84018444  1.15674054 -1.3487162 ]]
Random 1d Array Between 0 to 1: [0.21127545 0.52668586 0.51246756 0.94452233 0.16484725]
Random 2d Array Between 0 to 1: [[0.52954927 0.76520918 0.66354822 0.63927061 0.56988189]
 [0.02936216 0.75976064 0.87900012 0.99718695 0.22157148]
 [0.06925912 0.40993618 0.38414223 0.52047243 0.84664702]
 [0.8253504  0.96973788 0.87988983 0.12599586 0.81056954]]
Random 1d Array Between 0 to 1: [4 9 9 6 7 7]
